apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-learnify
  namespace: development
  labels:
    app: dev-learnify
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: dev-learnify
      tier: backend
  template:
    metadata:
      labels:
        app: dev-learnify
        tier: backend
    spec:
      containers:
      - name: dev-learnify
        image: eros-acr-ee-registry-vpc.ap-southeast-5.cr.aliyuncs.com/dev-poc/learnify:latest
        imagePullPolicy: Always
        resources: 
          limits:
            cpu: 60m
            memory: 240Mi
          requests:
            cpu: 30m
            memory: 120Mi
        ports:
        - containerPort: 8080
          name: dev-learnify
        env:
        - name: MYSQL_HOST_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: host_name
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db_name
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: other-secret
              key: encryption_key
      imagePullSecrets:
      - name: acr-secret
      restartPolicy: Always